-----EJECUTAR SCRIPT DESDE SYSTEM 
----CREACIÓN DE ROLES Y USUARIOS 
 -- BORRAR USUARIOS 
     DROP USER MD_SUPER CASCADE ;
     DROP USER MD_ADMIN;
     DROP USER MD_CONSULTOR_1;

----CREACION USUARIO 1
 
CREATE USER MD_SUPER IDENTIFIED BY "MD_SUPER"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MD_SUPER QUOTA 200 ON USERS;
GRANT CREATE SESSION TO MD_SUPER;
GRANT "RESOURCE" TO MD_SUPER;
GRANT CREATE ROLE TO MD_SUPER;
ALTER USER MD_SUPER DEFAULT ROLE "RESOURCE";
GRANT CREATE INDEXTYPE  TO MD_SUPER;
GRANT CREATE SEQUENCE TO MD_SUPER;
GRANT CREATE TABLE TO MD_SUPER;
GRANT  UPDATE ANY TABLE  TO MD_SUPER;
GRANT  DROP ANY TABLE TO MD_SUPER;
GRANT CREATE ANY INDEX TO MD_SUPER  ;
----DESDE USUARIO MD_SUPER EJECUTAR EL ARCHIVO DE  POBLACION DE TABLAS

---DESDE SYSTEM
---CREACION DE  SINONIMOS
---CREATE OR REPLACE PUBLIC SYNONYM SYN_DETALLE_ORDENES FOR MD_SUPER.DETALLE_ORDENES;
---CREATE OR REPLACE PUBLIC SYNONYM SYN_CATEGORIAS FOR MD_SUPER.CATEGORIAS;
--- CREATE OR REPLACE PUBLIC SYNONYM SYN_COMUNA FOR MD_SUPER.COMUNA;
---CREATE OR REPLACE PUBLIC SYNONYM SYN_REGION FOR MD_SUPER.REGION;
---CREATE OR REPLACE PUBLIC SYNONYM SYN_ORDENES FOR MD_SUPER.ORDENES;
---CREATE OR REPLACE PUBLIC SYNONYM SYN_PROVEEDORES FOR MD_SUPER.PROVEEDORES;
---CREATE OR REPLACE PUBLIC SYNONYM SYN_PRODUCTOS FOR MD_SUPER.PRODUCTOS;
---CREATE  OR REPLACE PUBLIC SYNONYM SYN_CLIENTES FOR MD_SUPER.CLIENTES;

---DESDE SYSTEM
--CREACION USUARIO 2
CREATE USER MD_ADMIN IDENTIFIED BY "MD_ADMIN"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MD_ADMIN QUOTA 200 ON USERS;
GRANT CREATE SESSION TO MD_ADMIN;
--CREAR FUNCIONES Y PETICIONES ACCESO A LAS TABLAS POR SINONIMOS
   --         GRANT CREATE VIEW TO MD_ADMIN;
   --         GRANT CREATE SEQUENCE TO MD_ADMIN;
   --         GRANT CREATE TRIGGER TO MD_ADMIN;
   --         
   --         GRANT INSERT ON SYN_CATEGORIAS TO MD_ADMIN;
   --         GRANT INSERT ON SYN_DETALLE_ORDENES TO MD_ADMIN;
   --         GRANT INSERT ON SYN_ORDENES TO MD_ADMIN;
   --         GRANT INSERT ON  SYN_PRODUCTOS  TO MD_ADMIN;
   --         
   --         GRANT  UPDATE ON  SYN_CATEGORIAS  TO MD_ADMIN;
   --         GRANT  UPDATE ON SYN_DETALLE_ORDENES TO MD_ADMIN;
   --         GRANT  UPDATE ON  SYN_ORDENES  TO MD_ADMIN;
   --         GRANT  UPDATE ON  SYN_PRODUCTOS  TO MD_ADMIN;
   --         
   --         GRANT  DELETE ON  SYN_ORDENES  TO MD_ADMIN;
   --         GRANT  DELETE ON SYN_DETALLE_ORDENES TO MD_ADMIN;
   --         GRANT  DELETE ON  SYN_CATEGORIAS  TO MD_ADMIN;
   --         GRANT  DELETE ON  SYN_PRODUCTOS  TO MD_ADMIN; 
   --         
   --         GRANT SELECT ON  SYN_PRODUCTOS TO MD_ADMIN;
   --         GRANT SELECT ON  SYN_CATEGORIAS TO MD_ADMIN;
   --         GRANT SELECT ON SYN_DETALLE_ORDENES TO MD_ADMIN;
   --         GRANT SELECT ON SYN_ORDENES TO MD_ADMIN;
   --         GRANT SELECT ON SYN_CLIENTES TO MD_ADMIN;
   --         GRANT SELECT ON SYN_PROVEEDORES TO MD_ADMIN ;
   --         GRANT SELECT ON SYN_COMUNA TO MD_ADMIN;
   --         GRANT SELECT ON SYN_REGION TO MD_ADMIN;
   --         GRANT SELECT ON SYN_PROVEEDORES to MD_ADMIN;

---DESDE SYSTEM
---CREACION DE ROLES
			CREATE ROLE ROL_CONSULTOR;
			GRANT CREATE SESSION TO ROL_CONSULTOR;
			GRANT SELECT ON SYN_DETALLE_ORDENES TO ROL_CONSULTOR;
			GRANT SELECT ON SYN_ORDENES TO ROL_CONSULTOR;
			GRANT SELECT ON SYN_CLIENTES TO ROL_CONSULTOR;
--- CREACION DE USUARIO CONSULTORES

		CREATE USER MD_CONSULTOR_1 IDENTIFIED BY "MD_CONSULTOR_1"
		DEFAULT TABLESPACE "USERS"
		TEMPORARY TABLESPACE "TEMP";
		ALTER USER MD_CONSULTOR_1 QUOTA 200 ON USERS;
		GRANT ROL_CONSULTOR to MD_CONSULTOR_1; --SE ASIGNA EL ROL

   